apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: failing-busybox
spec:
  containers:
  - args:
    - sh
    - -c
    - echo hello; sleep 10000
    image: busybox
    name: busybox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
