kind: Service
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ template "fullname" . }}-controller
  ports:
    - protocol: TCP
      port: 443
      targetPort: {{ .Values.config.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fullname" . }}-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-controller
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-controller
      annotations:
        sidecar.istio.io/inject: "false"
        checksum/config: {{ include (print $.Template.BasePath "/validating-webhook.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ template "fullname" . }}-sa
      containers:
        - name: webhook
          image: "{{ .Values.images.containerRegistry.path }}/webhook:{{ .Values.images.containerRegistry.tag }}"
          ports:
            - containerPort: {{ .Values.config.port }}
          imagePullPolicy: "{{ .Values.images.imagePullPolicy }}"
          volumeMounts:
            - name: webhook-cert
              mountPath: /var/run/webhook
              readOnly: true
          env:
            - name: APP_PORT
              value: "{{ .Values.config.port }}"
            - name: APP_LOG_LEVEL
              value: "{{ .Values.config.log.level }}"
            - name: APP_STACKTRACE_LEVEL
              value: "{{ .Values.config.log.stacktraceLevel }}"
            - name: APP_LOG_FORMAT
              value: "{{ .Values.config.log.format }}"
            - name: APP_VALIDATOR_SERVICE_ACCOUNT_DENY_LIST
              value: {{ .Values.config.serviceAccountDenyList }}
            - name: APP_VALIDATOR_NAMESPACE_DENY_LIST
              value: {{ .Values.config.namespaceDenyList }}
      volumes:
        - name: webhook-cert
          secret:
            secretName: {{ template "fullname" . }}-webhook-cert
