{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "webhook.name" .}}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "webhook.labels" . | nindent 4 }}
spec:
  minAvailable: 80%
  selector:
    matchLabels:
  {{- include "webhook.labels" . | nindent 6 }}
  {{- end }}