kind: Service
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ template "fullname" . }}-controller
  ports:
    - protocol: TCP
      port: 443
      targetPort: {{ .Values.config.port }}