kind: Service
apiVersion: v1
metadata:
  name: {{ template "webhook.svcFullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
  {{- include "webhook.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 443
      targetPort: {{ .Values.config.port }}