{{- $ca := genCA "service-catalog-webhook-ca" 3650 }}
{{- $cn := printf "%s-webhook" (include "fullname" .) }}
{{- $altName1 := printf "%s.%s" $cn .Release.Namespace }}
{{- $altName2 := printf "%s.%s.svc" $cn .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $altName1 $altName2) 3650 $ca }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-webhook-cert
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ template "fullname" . }}-validating-webhook
webhooks:
  - name: validating.pods.kyma-project.io
    clientConfig:
      caBundle: {{ b64enc $ca.Cert }}
      service:
        name: {{ template "fullname" . }}-webhook
        namespace: "{{ .Release.Namespace }}"
        path: "/pod-validating"
    failurePolicy: Ignore
    sideEffects: None
    timeoutSeconds: 5
    admissionReviewVersions:
      - v1
    rules:
      - apiGroups: ["*"]
        apiVersions: ["*"]
        operations: ["*"]
        resources: ["*"]
        scope: "*"
