images:
  containerRegistry:
    path: aerfio
  imagePullPolicy: Always
  bindingController:
    version: "v1"

config:
  port: 8443
  serviceAccountDenyList: "system:serviceaccount:default:test-deny"
  namespaceDenyList: "kyma-system,kyma-integration,\"\""
  log:
    level: "info"
    stacktraceLevel: "fatal"
    format: "text"
