image:
  registry: docker.io
  repository: aerfio/webhook
  tag: v3
  pullPolicy: Always # TODO: change this to IfNotPresent

deployment:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 100m
      memory: 200Mi

podAntiAffinity:
  enabled: true

podDisruptionBudget:
  enabled: true
  minAvailable: 80%

config:
  port: 8443
  metricsPort: 8080
  healthProbePort: 8081
  serviceAccountAllowList: "system:serviceaccount:default:test-allow"
  namespaceDenyList: kyma-system,kyma-integration,"" # "" means clusterwide
  log:
    level: "debug"
    stacktraceLevel: "error"
    format: "json"

priorityClass:
  enabled: true
  value: 1000000000 # needs to be lower than "system-cluster-critical" and "system-node-critical"