images:
  containerRegistry:
    path: aerfio
    tag: v1
  imagePullPolicy: Always

config:
  port: 8443
  serviceAccountDenyList: "system:serviceaccount:default:test-deny"
  namespaceDenyList: kyma-system,kyma-integration,clusterwide
  log:
    level: "info"
    stacktraceLevel: "error"
    format: "json"
