image:
  registry: docker.io
  repository: aerfio/webhook
  tag: v1
  pullPolicy: Always # TODO: change this to IfNotPresent

deployment:
  replicas: 1

config:
  port: 8443
  serviceAccountDenyList: "system:serviceaccount:default:test-deny"
  namespaceDenyList: kyma-system,kyma-integration,"" # "" means clusterwide
  log:
    level: "info"
    stacktraceLevel: "error"
    format: "json"
